# clang_format_version = 16
# cpp_std = "20"
project_name = "HPWHSim"
# project_short_description = ""
project_type = "cpp"
# start_year = 2025
# use_app = false
# use_cmake_version = false
# use_taskfile = false
# version_major = 0
# version_minor = 1
# version_patch = 0
# year = 2025
[[deps]]
name = "btwxt"
git_url = "https://github.com/bigladder/btwxt.git"
git_checkout = "main"
add_to_cmake = true
[[deps]]
name = "CLI11"
git_url = "https://github.com/CLIUtils/CLI11.git"
git_checkout = "b24c301"
add_to_cmake = true
[[deps]]
name = "json"
git_url = " https://github.com/nlohmann/json.git"
git_checkout = "main"
add_to_cmake = true
# [[deps]]
# name = "" # <- name of the dependency; vendor/<name>
# git_url = "" # <- add the url used to checkout this repository
# git_checkout = "" # <- add the branch, sha, or tag to check out
# add_to_cmake = true # <- if true, add to CMakeLists.txt files
# link_library_spec = "" # <- how library should appear in target_link_library(.); if blank, use project name