[tool.poetry]
name = "HPWHsim-python-scripts"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
pandas = "*"
plotly = "*"
koozie = "*"
dimes = { git = "https://github.com/bigladder/dimes" }
dash = "^2.18.2"
promptlib = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
