[project]
name = "HPWHsim-python-scripts"
version = "0.0.0"
description = ""
authors = []
requires-python = "~=3.8"
dependencies = [
    "pandas",
    "plotly",
    "koozie",
    "dimes",
]

[tool.uv]

[tool.uv.sources]
dimes = { git = "https://github.com/bigladder/dimes" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
