[tool.poetry]
name = "HPWHsim-python-scripts"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<4.0" #"^3.8"
pandas = "*"
plotly = "*"
koozie = "*"
dimes = { git = "https://github.com/bigladder/dimes" }
dash-extensions = "^1.0.19"
websockets = "^14.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
