
#ifndef HPWH_DATA_MODEL_EXPORT_H
#define HPWH_DATA_MODEL_EXPORT_H

#ifdef HPWH_DATA_MODEL_STATIC_DEFINE
#define HPWH_DATA_MODEL_EXPORT
#define HPWH_DATA_MODEL_NO_EXPORT
#else
#ifndef HPWH_DATA_MODEL_EXPORT
#ifdef hpwh_data_model_EXPORTS
/* We are building this library */
#define HPWH_DATA_MODEL_EXPORT
#else
/* We are using this library */
#define HPWH_DATA_MODEL_EXPORT
#endif
#endif

#ifndef HPWH_DATA_MODEL_NO_EXPORT
#define HPWH_DATA_MODEL_NO_EXPORT
#endif
#endif

#ifndef HPWH_DATA_MODEL_DEPRECATED
#define HPWH_DATA_MODEL_DEPRECATED __attribute__((__deprecated__))
#endif

#ifndef HPWH_DATA_MODEL_DEPRECATED_EXPORT
#define HPWH_DATA_MODEL_DEPRECATED_EXPORT HPWH_DATA_MODEL_EXPORT HPWH_DATA_MODEL_DEPRECATED
#endif

#ifndef HPWH_DATA_MODEL_DEPRECATED_NO_EXPORT
#define HPWH_DATA_MODEL_DEPRECATED_NO_EXPORT HPWH_DATA_MODEL_NO_EXPORT HPWH_DATA_MODEL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#ifndef HPWH_DATA_MODEL_NO_DEPRECATED
#define HPWH_DATA_MODEL_NO_DEPRECATED
#endif
#endif

#endif /* HPWH_DATA_MODEL_EXPORT_H */
