[project]
name = "data-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lattice",
]

[tool.uv.sources]
lattice = { git = "https://github.com/bigladder/lattice", branch = "main" }
