#ifndef HPWHUTILS_hh
#define HPWHUTILS_hh

//-----------------------------------------------------------------------------
///	@brief	assign t_new to t if is_set, else assign t_default
//-----------------------------------------------------------------------------
template <typename T>
void checkFrom(T& t, const bool is_set, const T t_new, const T t_default)
{
    t = is_set ? t_new : t_default;
}

//-----------------------------------------------------------------------------
///	@brief	assign t_new to t if j contains key, else assign t_default
//-----------------------------------------------------------------------------
template <typename T>
bool checkFrom(T& t, nlohmann::json& j, std::string_view key, const T t_default)
{
    bool has_key = false;
    if (j.contains(key))
    {
        has_key = true;
        t = j[key];
    }
    else
        t = t_default;
    return has_key;
}

//-----------------------------------------------------------------------------
///	@brief	set t to t_new if has_value
//-----------------------------------------------------------------------------
template <typename T>
void checkTo(const T t, bool& is_set, T& t_new, const bool has_value = true)
{
    is_set = has_value;
    if (has_value)
    {
        t_new = t;
    }
}

//-----------------------------------------------------------------------------
///	@brief	Generate metadata and transfer to json
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void generate_json_metadata(const std::string& schema_name, const std::string& schema_url, nlohmann::json& j_metadata)
{
    j_metadata = {};
    j_metadata["schema_author"] = "Big Ladder Software, LLC";
    j_metadata["author"] = "California Energy Commission";
    j_metadata["description"] = "Representation of embedded HPWH element";
    j_metadata["source"] = "Generated by HPWHsim";
    j_metadata["schema_version"] = RSTYPE::schema_version;
    j_metadata["schema_name"] = schema_name;
    j_metadata["schema_url"] = schema_url;

    time_t t = time(NULL);
    char buf[sizeof "2011-10-08T07:07:09Z"];

#if defined(WIN32)
    struct tm gmt;
    gmtime_s(&gmt, &t);
    strftime(buf, sizeof(buf), "%FT%TZ", &gmt);
#else
    auto ts = gmtime(&t);
    std::strftime(buf, sizeof(buf), "%FT%RZ", ts);
#endif
    j_metadata["time_of_creation"] = buf;
}

//-----------------------------------------------------------------------------
///	@brief	Transfer Metadata from schema
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void get_metadata_as_json(const RSTYPE& rs, nlohmann::json& j_metadata)
{
    j_metadata = {};
    if (rs.metadata_is_set)
    {
        auto& metadata = rs.metadata;
        if (metadata.schema_author_is_set)
            j_metadata["schema_author"] = metadata.schema_author;
        if (metadata.author_is_set)
            j_metadata["author"] = metadata.author;
        if (metadata.description_is_set)
            j_metadata["description"] = metadata.description;
        if (metadata.source_is_set)
            j_metadata["source"] = metadata.source;
        if (metadata.schema_version_is_set)
            j_metadata["schema_version"] = metadata.schema_version;
        if (metadata.time_of_creation_is_set)
            j_metadata["time_of_creation"] = metadata.time_of_creation;
        if (metadata.time_of_creation_is_set)
            j_metadata["time_of_creation"] = metadata.time_of_creation;
        if (metadata.time_of_creation_is_set)
            j_metadata["time_of_creation"] = metadata.time_of_creation;
    }
}

//-----------------------------------------------------------------------------
///	@brief	Transfer Metadata to schema
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void json_to_metadata(const nlohmann::json& j_metadata, RSTYPE& rs)
{
   auto& metadata = rs.metadata;
   if (j_metadata.contains("schema_author"))
   {
        metadata.schema_author_is_set = true;
        metadata.schema_author = j_metadata["schema_author"];
   }
   if (j_metadata.contains("author"))
   {
        metadata.author_is_set = true;
        metadata.author = j_metadata["author"];
   }
   if (j_metadata.contains("description"))
   {
        metadata.description_is_set = true;
        metadata.description = j_metadata["description"];
   }
   if (j_metadata.contains("schema_author"))
   {
        metadata.schema_version_is_set = true;
        metadata.schema_version = j_metadata["schema_version"];
   }
   if (j_metadata.contains("time_of_creation"))
   {
        metadata.time_of_creation_is_set = true;
        metadata.time_of_creation = j_metadata["time_of_creation"];
   }
   if (j_metadata.contains("schema_name"))
   {
        metadata.time_of_creation_is_set = true;
        metadata.time_of_creation = j_metadata["schema_name"];
   }
   {
        metadata.schema_url_is_set = true;
        metadata.schema_url = j_metadata["schema_url"];
   }
   bool metadata_set = !j_metadata.empty();
   checkTo(metadata, rs.metadata_is_set, rs.metadata, metadata_set);
}

nlohmann::json& findMetadata(nlohmann::json& j)
{
   if (j.empty())
        j["metadata"] = {};
   return j["metadata"];
}

void placeMetadata(const nlohmann::json& j_metadata, nlohmann::json& j)
{
    if (!j_metadata.empty())
       j["metadata"] = j_metadata;
}

//-----------------------------------------------------------------------------
///	@brief	Transfer ProductInformation from schema to json repr
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void productInformation_to_json(const RSTYPE& rs, nlohmann::json& j_productInformation)
{
    j_productInformation = {};
    if (rs.description_is_set)
    {
        auto& desc = rs.description;
        if (desc.product_information_is_set)
        {
            auto& info = desc.product_information;
            if (info.manufacturer_is_set)
                j_productInformation["manufacturer"] = info.manufacturer;
            if (info.model_number_is_set)
                j_productInformation["model_number"] = info.model_number;
        }
    }
 }

//-----------------------------------------------------------------------------
///	@brief	Transfer ProductInformation to schema
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void productInformation_from_json(RSTYPE& rs, const nlohmann::json& j_productInformation)
{
    auto& desc = rs.description;
    auto& prod_info = desc.product_information;

    if (j_productInformation.contains("manufacturer"))
    {
        prod_info.manufacturer_is_set = true;
        prod_info.manufacturer = j_productInformation["manufacturer"];
    }

    if (j_productInformation.contains("model_number"))
    {
        prod_info.model_number_is_set = true;
        prod_info.model_number = j_productInformation["model_number"];
    }

    bool prod_info_set = prod_info.manufacturer_is_set || prod_info.model_number_is_set;
    checkTo(prod_info, desc.product_information_is_set, desc.product_information, prod_info_set);

    bool desc_set = prod_info_set;
    checkTo(desc, rs.description_is_set, rs.description, desc_set);
}

bool findProductInformation(nlohmann::json *j_productInformation, const nlohmann::json& j)
{
    if (!j.empty())
        if (j.contains("description"))
            if (j["description"].contains("product_information"))
                j_productInformation = j["description"]["product_information"];
}

void placeProductInformation(const nlohmann::json& j_productInformation, nlohmann::json& j)
{
    if (!j_productInformation.empty())
    {
        if (!j.contains("description"))
            j["description"] = {};
        j["description"]["product_information"] = j_productInformation;
    }
}

//-----------------------------------------------------------------------------
///	@brief	Transfer Rating10CFR430 from schema
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void rating10CFR430_to_json(const RSTYPE& rs, nlohmann::json& j_rating10CFR430)
{
    j_rating10CFR430 = {};
    if (rs.description_is_set)
    {
        auto& desc = rs.description;
        if (desc.rating_10_cfr_430_is_set)
        {
            auto& data = desc.rating_10_cfr_430;
            if (data.certified_reference_number_is_set)
                j_rating10CFR430["certified_reference_number"] = data.certified_reference_number;
            if (data.nominal_tank_volume_is_set)
                j_rating10CFR430["nominal_tank_volume"] = data.nominal_tank_volume;
            if (data.first_hour_rating_is_set)
                j_rating10CFR430["first_hour_rating"] = data.first_hour_rating;
            if (data.recovery_efficiency_is_set)
                j_rating10CFR430["recovery_efficiency"] = data.recovery_efficiency;
            if (data.uniform_energy_factor_is_set)
                j_rating10CFR430["uniform_energy_factor"] = data.uniform_energy_factor;
        }
    }
}

//-----------------------------------------------------------------------------
///	@brief	Transfer Rating10CFR430 to schema
//-----------------------------------------------------------------------------
template <typename RSTYPE>
void rating10CFR430_from_json(const nlohmann::json& j_rating10CFR430, RSTYPE& rs)
{
    auto& desc = rs.description;
    auto& data = desc.rating_10_cfr_430;

    if ((data.certified_reference_number_is_set =
             j_rating10CFR430.contains("certified_reference_number")))
        data.certified_reference_number = j_rating10CFR430["certified_reference_number"];

    if ((data.nominal_tank_volume_is_set = j_rating10CFR430.contains("nominal_tank_volume")))
        data.nominal_tank_volume = j_rating10CFR430["nominal_tank_volume"];

    if ((data.first_hour_rating_is_set = j_rating10CFR430.contains("first_hour_rating")))
        data.first_hour_rating = j_rating10CFR430["first_hour_rating"];

    if ((data.recovery_efficiency_is_set = j_rating10CFR430.contains("recovery_efficiency")))
        data.recovery_efficiency = j_rating10CFR430["recovery_efficiency"];

    if ((data.uniform_energy_factor_is_set = j_rating10CFR430.contains("uniform_energy_factor")))
        data.uniform_energy_factor = j_rating10CFR430["uniform_energy_factor"];

    desc.rating_10_cfr_430_is_set |= !j_rating10CFR430.empty();
    rs.description_is_set |= desc.rating_10_cfr_430_is_set;
}

void findRating10CFR430(nlohmann::json& j_rating10CFR430, const nlohmann::json& j)
{
    if (!j.empty())
        if (j.contains("description"))
            if (j["description"].contains("rating_10_cfr_430"))
                j_rating10CFR430 = j["description"]["rating_10_cfr_430"];
}

void placeRating10CFR430(const nlohmann::json& j_rating10CFR430, nlohmann::json& j)
{
    if (!j_rating10CFR430.empty())
    {
        if (!j.contains("description"))
            j["description"] = {};
        j["description"]["rating_10_cfr_430"] = j_rating10CFR430;
    }
}
#endif
